---
apiVersion: v1
kind: Service
metadata:
  name: ameyali-notebook-store
spec:
  ports:
  - port: 8000
  selector:
    app: ameyali-notebook-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ameyali-notebook-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ameyali-notebook-store
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ameyali-notebook-store
    spec:
      containers:
      - name: ameyali-notebook-store
        image: gcr.io/<PROJECT_ID>/ameyali-notebook-store-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: AWS_BUCKET
          value: "ameyali-notebook-store-s3"
        - name: S3_ACCESS_KEY
          value: "AKIATRSTTZDOLW5KVW2O"
        - name: S3_SECRET_ACCESS_KEY
          value: "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"
        - name: DB_HOST_NAME
          value: "172.21.0.3"
        - name: DB_USER
          value: "appdbusr"
        - name: DB_PASSWORD
          value: "Welcome123"
        - name: DB_NAME
          value: "dbameyali"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: ameyali-notebook-store
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: ameyali-notebook-store